{
 "title": "股票撮合系统监控大盘",
 "tags": [
  "trading-simulator",
  "order",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "服务实例/Job",
    "query": {
     "query": "label_values(trading_order_success_total,job)"
    }
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "01核心交易健康度概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(trading_order_success_total{job=~\"$job\"}[10m])) \r\n/ \r\nclamp_min(sum(increase(trading_order_total{job=~\"$job\"}[10m])), 1)",
     "legendFormat": "订单申报成功率(10min)"
    },
    {
     "expr": "sum(increase(trading_order_reject_total{job=~\"$job\"}[10m])) \r\n/ \r\nclamp_min(sum(increase(trading_order_total{job=~\"$job\"}[10m])), 1)",
     "legendFormat": "订单申报拒绝率"
    }
   ]
  },
  {
   "title": "C",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trading_orderbook_buy_total_size{job=~\"$job\"}) + sum(trading_orderbook_sell_total_size{job=~\"$job\"})",
     "legendFormat": "订单簿总挂单量"
    },
    {
     "expr": "trading_orderbook_buy_total_size",
     "legendFormat": "买单"
    },
    {
     "expr": "trading_orderbook_sell_total_size",
     "legendFormat": "卖单"
    }
   ]
  },
  {
   "title": "B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(trading_trade_total{job=~\"$job\"}[3h])) + sum(increase(trading_trade_recovery_total{job=~\"$job\"}[3h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "D",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(trading_consistency_check_mismatch_total{job=~\"$job\"}[3h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "02订单申报与校验全链路监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "2.A",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(trading_order_total{job=~\"$job\"}[10m]))",
     "legendFormat": "订单总请求速率"
    },
    {
     "expr": "sum(rate(trading_order_success_total{job=~\"$job\"}[10m]))",
     "legendFormat": "订单成功速率"
    },
    {
     "expr": "sum(rate(trading_order_failed_total{job=~\"$job\"}[10m]))",
     "legendFormat": "订单总请求失败速率"
    },
    {
     "expr": "sum(rate(trading_order_reject_total{job=~\"$job\"}[10m]))",
     "legendFormat": "订单总请求拒绝订单速率"
    }
   ]
  },
  {
   "title": "2.B",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(trading_order_validate_pass_total{job=~\"$job\"}[10m]))",
     "legendFormat": "校验通过次数（10分钟内）"
    },
    {
     "expr": "sum(increase(trading_order_validate_fail_total{job=~\"$job\"}[10m]))",
     "legendFormat": "校验失败次数（10分钟内）"
    }
   ]
  },
  {
   "title": "2.C",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trading_order_success_total", "legendFormat": "交易总成功数" },
    { "expr": "trading_order_failed_total", "legendFormat": "交易总失败数" },
    { "expr": "trading_order_reject_total", "legendFormat": "交易总拒绝数" }
   ]
  },
  {
   "title": "2.D",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(trading_order_reject_total{job=~\"$job\"}[10m])) / clamp_min(sum(rate(trading_order_total{job=~\"$job\"}[10m])), 1)",
     "legendFormat": "订单申报拒绝错单率（10m滑动窗口）"
    },
    {
     "expr": "sum(rate(trading_order_failed_total{job=~\"$job\"}[10m])) / clamp_min(sum(rate(trading_order_total{job=~\"$job\"}[10m])), 1)",
     "legendFormat": "订单申报失败率（10m滑动窗口）"
    }
   ]
  },
  { "title": "03撤单全链路流量时序图", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "撤单全链路流量时序图",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trading_cancel_success_total", "legendFormat": "成功撤单数" },
    { "expr": "trading_cancel_failed_total", "legendFormat": "失败撤单数" },
    { "expr": "trading_cancel_reject_total", "legendFormat": "撤单拒绝数" }
   ]
  },
  { "title": "04数据持久化", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "4.A",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trading_persist_success_total", "legendFormat": "持久化成功" },
    { "expr": "trading_persist_fail_total", "legendFormat": "持久化最终失败" },
    { "expr": "trading_persist_retry_total", "legendFormat": "持久化重试" }
   ]
  },
  { "title": "05数据一致性合规监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "一致性检测（开发辅助）",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trading_consistency_check_total",
     "legendFormat": "总检测单量"
    },
    {
     "expr": "trading_consistency_check_failed_total",
     "legendFormat": "一致性检测失败数量（开发过程辅助）"
    },
    {
     "expr": "trading_consistency_check_mismatch_total",
     "legendFormat": "不匹配数量"
    }
   ]
  },
  { "title": "06-时间统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "平均耗时（Average Latency, 单位：ms）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "1000 *(rate(trading_order_process_time_seconds_sum[1h])\r\n/\r\nrate(trading_order_process_time_seconds_count[1h]))",
     "legendFormat": "订单处理平均耗时"
    },
    {
     "expr": "1000 *(rate(trading_cancel_process_time_seconds_sum[1h])\r\n/\r\nrate(trading_cancel_process_time_seconds_count[1h]))",
     "legendFormat": "撤单平均耗时"
    },
    {
     "expr": "1000 *(rate(trading_order_match_time_seconds_sum[1h])\r\n/\r\nrate(trading_order_match_time_seconds_count[1h]))",
     "legendFormat": "撮合平均耗时"
    }
   ]
  },
  {
   "title": "最大耗时（Max Latency）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 44 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(\r\n  0.99,\r\n  sum(rate(trading_order_process_time_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "订单处理最大耗时"
    },
    {
     "expr": "1000*histogram_quantile(\r\n  0.99,\r\n  sum(rate(trading_cancel_process_time_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "撤单请求最大耗时"
    },
    {
     "expr": "1000*histogram_quantile(\r\n  0.99,\r\n  sum(rate(trading_order_match_time_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "撮合过程最大耗时"
    }
   ]
  },
  {
   "title": "吞吐量（Trading Throughput）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(trading_order_success_total[1m]) + rate(trading_cancel_success_total[1m])",
     "legendFormat": "成功下单TPS + 成功撤单TPS = 总成功TPS"
    },
    {
     "expr": "rate(trading_cancel_success_total[1m])",
     "legendFormat": "撤单请求处理TPS"
    }
   ]
  }
 ]
}